"""empty message

Revision ID: 6c80d4be39ac
Revises: d60e7a44c640
Create Date: 2026-04-17 23:55:38.747459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c80d4be39ac'
down_revision: Union[str, Sequence[str], None] = 'd60e7a44c640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('source_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_jobs_source_id_job_sources'), 'jobs', 'job_sources', ['source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_jobs_source_id_job_sources'), 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'source_id')
    # ### end Alembic commands ###
