"""empty message

Revision ID: d60e7a44c640
Revises: 96d1db5cba41
Create Date: 2026-04-17 23:19:41.979545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd60e7a44c640'
down_revision: Union[str, Sequence[str], None] = '96d1db5cba41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_sources', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('job_sources', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('job_sources', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_sources', 'updated_at')
    op.drop_column('job_sources', 'created_at')
    op.drop_column('job_sources', 'is_active')
    # ### end Alembic commands ###
